version: '3'
services:
  postgres:
    image: postgres:13.2
    container_name: postgres
    ports:
      - 25432:5432
    volumes:
      # - database:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8'
    networks:
      - postgres

  pgadmin4:
    image: dpage/pgadmin4:5
    container_name: pgadmin
    ports:
      - 20080:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@dummy.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    networks:
      - postgres
    depends_on:
      - postgres

volumes:
  database:
    driver: local
  pgadmin:
    driver: local

networks:
  postgres:
    driver: bridge
