CREATE TABLE TBM_USER (
    USER_ID VARCHAR(6) NOT NULL,
    EMAIL VARCHAR(254),
    PASSWORD VARCHAR(128),
    DELETE_FLAG VARCHAR(1)
);

ALTER TABLE TBM_USER
ADD CONSTRAINT PK_TBM_USER
PRIMARY KEY (
    USER_ID
);
